version: '2'


services:
  counter_db:
    image: mariadb:latest
    environment:
        - MYSQL_ROOT_PASSWORD=P@ssw0rd$$
        - MYSQL_DATABASE=web_counter
        - MYSQL_USER=web_counter
        - MYSQL_PASSWORD=P@ssw0rd!
    ports:
        - "3306"
    volumes:
        - ./counter_sql:/docker-entrypoint-initdb.d
    networks:
      back-tier:
        aliases:
          - counter_mariadb
    
  forum_db:
    image: postgres:latest
    environment:
        - POSTGRES_PASSWORD=P@ssw0rd!
        - POSTGRES_DB=forum
        - POSTGRES_USER=forum
    ports:
        - "5432"
    volumes:
        - ./forum_sql:/docker-entrypoint-initdb.d
    networks:
      back-tier:
        aliases:
          - forum_mariadb
  
  web:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - ./counter_code:/counter_code
        - ./forum_code:/forum_code
        - ./nginx.conf:/etc/nginx/nginx.conf
    links:
        - counter_php
        - forum_python
    networks:
        - front-tier
  
  counter_php:
    image: evergreenitco/php7-fpm_mysqlcli
    environment:
        - COUNTER_MYSQL_DATABASE=web_counter
        - COUNTER_MYSQL_USER=web_counter
        - COUNTER_MYSQL_PASSWORD=P@ssw0rd!
        - COUNTER_CODE_VERSION=2.0.0
    ports:
        - "9000"
    volumes:
        - ./counter_code:/counter_code
    links:
        - counter_db
    networks:
        - front-tier
        - back-tier

  forum_python:
    image: evergreenitco/python_2.7_psycopg2_bleach:latest
    command: [ "python", "/forum_code/forum.py" ]
    environment:
        - FORUM_POSTGRES_PASSWORD=P@ssw0rd!
        - FORUM_POSTGRES_DB=forum
        - FORUM_POSTGRES_USER=forum
    ports:
        - "9090"
    volumes:
        - ./forum_code:/forum_code
    links:
        - forum_db
    networks:
        - front-tier
        - back-tier

networks:
  front-tier:
  back-tier:

